apiVersion: v1
kind: Service
metadata:
  name: uvicorn-app
spec:
  type: ClusterIP
  selector:
    app: uvicorn-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
