apiVersion: v1
kind: Service
metadata:
  name: uvicorn-app-v2
spec:
  type: {{ .Values.service.type }}

  selector:
    app: uvicorn-app
    version: v2

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
