replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/cert-project-492718/mcp/uvicorn-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8081

ingress:
  enabled: true
  className: gce-internal
  staticIpName: my-internal-ip
  path: /

resources: {}

readinessProbe:
  path: /health
  port: 8081

livenessProbe:
  path: /health
  port: 8081
