replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/cert-project-492718/mcp/uvicorn-app
  tag: latest
  pullPolicy: Always

service:
  port: 80
  targetPort: 8081

nginx:
  internalIp: 10.128.15.199

resources: {}

readinessProbe:
  path: /health
  port: 8081

livenessProbe:
  path: /health
  port: 8081
