replicaCount: 5

image:
  repository: us-central1-docker.pkg.dev/cert-project-492718/mcp/uvicorn-app
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8081

resources: {}

readinessProbe:
  path: /health
  port: 8081

livenessProbe:
  path: /health
  port: 8081
